### ISSUE TITLE
No dependency on pudb module

### ISSUE THREAD

**Issue by tomersa** [ogofen/ovirtremote#1]
Hi,

There is no dependency in the installer on the pudb module. You should add it.

That's what I received(I deliberately tried malformed command but it is not related to the dependency I think):
$ ovirt-remote get domains_info
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ovirtremote/run.py", line 2, in <module>
    from classes._ovirtremote import ovirtremote
  File "/usr/lib/python2.7/site-packages/ovirtremote/classes/_ovirtremote.py", line 5, in <module>
    from set import Set
  File "/usr/lib/python2.7/site-packages/ovirtremote/classes/set.py", line 2, in <module>
    import pudb
ImportError: No module named pudb

**Comment by ogofen** [comment]
fixed
